### ISSUE TITLE
nickel.rs DNS not resolving

### ISSUE THREAD

**Issue by bltavares** [nickel-org/nickel-org.github.io#14] opened 2017-07-16 18:10 UTC
Hi there @cburgdorf, @Ryman and @SimonPersson,

I was not sure how to bring visibility about it, but it seems that the DNS for the http://nickel.rs website could be expired or misconfigured.

I've tried connecting and I got a `ERR_NAME_NOT_RESOLVED` from Chrome on my computer, and IsItUp.org also reported an error.

<img width="1054" alt="screen shot 2017-07-16 at 15 06 09" src="https://user-images.githubusercontent.com/109474/28250125-5a75748a-6a38-11e7-93f1-757408651d8c.png">
<img width="1106" alt="screen shot 2017-07-16 at 15 05 24" src="https://user-images.githubusercontent.com/109474/28250126-5a76c484-6a38-11e7-91fe-6dd515e31d0d.png">

I've tried `dig` and there seems to be no CNAME or A configured for the domain.

<details>
<summary>dig nickel.rs @8.8.8.8</summary>
; <<>> DiG 9.8.3-P1 <<>> nickel.rs @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 7097
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;nickel.rs.			IN	A

;; AUTHORITY SECTION:
rs.			1799	IN	SOA	a.nic.rs. hostmaster.nic.rs. 2017071609 3600 1800 2419200 3600

;; Query time: 62 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Jul 16 15:07:17 2017
;; MSG SIZE  rcvd: 80
</details>

Let me know if there are further tests to help debug it

**Comment by jolhoeft** [comment] 2017-07-25 20:52
Domain has expired:

$ whois nickel.rs
%
%This is the RNIDS Whois server.
%
% Date Format         : DD.MM.YYYY
% Whois Server Version: 1.0.0
%
% Rights restricted by copyright.
% See http://www.rnids.rs/whois_en
%
%
%
% Ovo je odgovor od RNIDS Whois servera.
%
% Format datuma     : DD.MM.YYYY
% Verzija Whois Servera : 1.0.0
%
% Sva prava zadržana. Za više informacija.
% pogledajte http://www.rnids.rs/whois_sr

Domain name: nickel.rs
Domain status: Expired, clientUpdateProhibited
Registration date: 15.07.2014 21:42:05
Modification date: 07.04.2017 11:31:35
Expiration date: 15.07.2017 21:42:05
Registrar: NINET Company d.o.o.

**Comment by cburgdorf** [comment] 2017-07-25 21:37
Yep, the problem is that the company NINET did not respond to any of my emails to continue the service. Does anyone know about a better registrar for .rs domains? Meanwhile I'm trying to contact them again.

**Comment by jolhoeft** [comment] 2017-08-15 22:38
Any luck with the DNS? Do we want to consider moving to a different registar, possibly with a new domain if necessary?

**Comment by cburgdorf** [comment] 2017-09-08 20:37
I removed the CNAME files so that the website can now be served from gh-pages directly. Also changed links in the README. http://nickel-org.github.io/

**Closed by cburgdorf** 2017-09-08 20:37 UTC
